export type GoalEnvironmentType = 'low' | 'medium-low' | 'medium' | 'medium-high' | 'high';
export type VarianceType = 'low' | 'medium' | 'medium-high' | 'high';
export type MarketLiquidityType = 'high' | 'medium' | 'low';
export type CompetitionStatus = 'ACTIVE' | 'BETA' | 'DISABLED';

export interface CompetitionProfileConfig {
  goalEnvironment: GoalEnvironmentType;
  homeAdvantage: number;
  variance: VarianceType;
  fatigueSensitivity: number;
  marketLiquidity: MarketLiquidityType;
}

export interface LeagueConfig {
  id: string;
  name: string;
  country: string;
  type: 'club' | 'international';
  enabled: boolean;
  marketPriority: ('AH' | 'OU' | 'ML')[];
  profile: CompetitionProfileConfig;
  marketSuitability: {
    AH: boolean;
    OU: boolean;
    ML: boolean;
  };
  apiFootballId: number;
  footballDataId?: number;
  oddsApiSportKey?: string;
  status: CompetitionStatus;
  cohort: 'WORLD_CUP' | 'EPL' | 'LIGUE2' | 'EUROPA' | 'OTHER';
  minimumHistoricalMatches?: number;
  priority: number; // Ingestion / calculation priority: 1 (highest) to 3 (lowest)
  competition_type: 'league' | 'cup' | 'international_tournament';
  activation?: {
    start: string;
    end?: string;
  };
  tier?: number;
  liquidity_score?: number;
  market_coverage_score?: number;
  validation_priority?: 'A' | 'B' | 'C';
  
  // Sprint 10 validation dataset fields
  is_active_now: boolean;
  expected_fixture_frequency: 'high' | 'medium' | 'low';
  market_liquidity_score: number;
}

export const LEAGUE_REGISTRY: LeagueConfig[] = [
  // --- ORIGINAL LEAGUES ---
  {
    id: 'world_cup_2026',
    name: 'FIFA World Cup',
    country: 'World',
    type: 'international',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: {
      goalEnvironment: 'medium-low',
      homeAdvantage: 1.02,
      variance: 'high',
      fatigueSensitivity: 1.3,
      marketLiquidity: 'high'
    },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 1,
    footballDataId: 2000,
    oddsApiSportKey: 'soccer_fifa_world_cup',
    status: 'ACTIVE',
    cohort: 'WORLD_CUP',
    minimumHistoricalMatches: 3,
    priority: 1,
    competition_type: 'international_tournament',
    activation: {
      start: '2026-06-11',
      end: '2026-07-19'
    },
    tier: 1,
    liquidity_score: 95,
    market_coverage_score: 100,
    validation_priority: 'A',
    is_active_now: false,
    expected_fixture_frequency: 'low',
    market_liquidity_score: 95
  },
  {
    id: 'uefa_champions_league',
    name: 'UEFA Champions League',
    country: 'Europe',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: {
      goalEnvironment: 'medium',
      homeAdvantage: 1.08,
      variance: 'high',
      fatigueSensitivity: 1.2,
      marketLiquidity: 'high'
    },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 2,
    footballDataId: 2001,
    status: 'ACTIVE',
    cohort: 'EUROPA',
    minimumHistoricalMatches: 5,
    priority: 1,
    competition_type: 'cup',
    tier: 1,
    liquidity_score: 95,
    market_coverage_score: 100,
    validation_priority: 'A',
    is_active_now: false,
    expected_fixture_frequency: 'high',
    market_liquidity_score: 95
  },
  {
    id: 'uefa_europa_league',
    name: 'UEFA Europa League',
    country: 'Europe',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: {
      goalEnvironment: 'medium',
      homeAdvantage: 1.08,
      variance: 'medium-high',
      fatigueSensitivity: 1.1,
      marketLiquidity: 'high'
    },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 3,
    status: 'ACTIVE',
    cohort: 'EUROPA',
    minimumHistoricalMatches: 5,
    priority: 1,
    competition_type: 'cup',
    tier: 1,
    liquidity_score: 85,
    market_coverage_score: 100,
    validation_priority: 'A',
    is_active_now: false,
    expected_fixture_frequency: 'high',
    market_liquidity_score: 85
  },
  {
    id: 'eng_premier_league',
    name: 'Premier League',
    country: 'England',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: {
      goalEnvironment: 'medium-high',
      homeAdvantage: 1.12,
      variance: 'medium',
      fatigueSensitivity: 1.0,
      marketLiquidity: 'high'
    },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 39,
    footballDataId: 2021,
    status: 'ACTIVE',
    cohort: 'EPL',
    minimumHistoricalMatches: 10,
    priority: 2,
    competition_type: 'league',
    tier: 1,
    liquidity_score: 100,
    market_coverage_score: 100,
    validation_priority: 'A',
    is_active_now: false,
    expected_fixture_frequency: 'high',
    market_liquidity_score: 100
  },
  {
    id: 'esp_la_liga',
    name: 'La Liga',
    country: 'Spain',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: {
      goalEnvironment: 'medium',
      homeAdvantage: 1.12,
      variance: 'medium',
      fatigueSensitivity: 1.0,
      marketLiquidity: 'high'
    },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 140,
    footballDataId: 2014,
    status: 'ACTIVE',
    cohort: 'OTHER',
    minimumHistoricalMatches: 10,
    priority: 2,
    competition_type: 'league',
    tier: 1,
    liquidity_score: 90,
    market_coverage_score: 100,
    validation_priority: 'A',
    is_active_now: false,
    expected_fixture_frequency: 'high',
    market_liquidity_score: 90
  },
  {
    id: 'ita_serie_a',
    name: 'Serie A',
    country: 'Italy',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: {
      goalEnvironment: 'medium-low',
      homeAdvantage: 1.12,
      variance: 'medium',
      fatigueSensitivity: 1.0,
      marketLiquidity: 'medium'
    },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 135,
    footballDataId: 2019,
    status: 'ACTIVE',
    cohort: 'OTHER',
    minimumHistoricalMatches: 10,
    priority: 2,
    competition_type: 'league',
    tier: 2,
    liquidity_score: 75,
    market_coverage_score: 100,
    validation_priority: 'A',
    is_active_now: false,
    expected_fixture_frequency: 'high',
    market_liquidity_score: 75
  },
  {
    id: 'ger_bundesliga',
    name: 'Bundesliga',
    country: 'Germany',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: {
      goalEnvironment: 'high',
      homeAdvantage: 1.12,
      variance: 'medium-high',
      fatigueSensitivity: 1.0,
      marketLiquidity: 'high'
    },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 78,
    footballDataId: 2002,
    status: 'ACTIVE',
    cohort: 'OTHER',
    minimumHistoricalMatches: 10,
    priority: 2,
    competition_type: 'league',
    tier: 1,
    liquidity_score: 90,
    market_coverage_score: 100,
    validation_priority: 'A',
    is_active_now: false,
    expected_fixture_frequency: 'high',
    market_liquidity_score: 90
  },
  {
    id: 'fra_ligue_1',
    name: 'Ligue 1',
    country: 'France',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: {
      goalEnvironment: 'medium',
      homeAdvantage: 1.12,
      variance: 'medium',
      fatigueSensitivity: 1.0,
      marketLiquidity: 'medium'
    },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 61,
    footballDataId: 2015,
    status: 'ACTIVE',
    cohort: 'OTHER',
    minimumHistoricalMatches: 10,
    priority: 2,
    competition_type: 'league',
    tier: 2,
    liquidity_score: 70,
    market_coverage_score: 100,
    validation_priority: 'A',
    is_active_now: false,
    expected_fixture_frequency: 'high',
    market_liquidity_score: 70
  },
  {
    id: 'uefa_conference_league',
    name: 'UEFA Conference League',
    country: 'Europe',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: {
      goalEnvironment: 'medium',
      homeAdvantage: 1.08,
      variance: 'medium',
      fatigueSensitivity: 1.0,
      marketLiquidity: 'medium'
    },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 844,
    status: 'ACTIVE',
    cohort: 'OTHER',
    minimumHistoricalMatches: 5,
    priority: 3,
    competition_type: 'cup',
    tier: 2,
    liquidity_score: 65,
    market_coverage_score: 100,
    validation_priority: 'A',
    is_active_now: false,
    expected_fixture_frequency: 'low',
    market_liquidity_score: 65
  },
  {
    id: 'fra_ligue_2',
    name: 'Ligue 2',
    country: 'France',
    type: 'club',
    enabled: false,
    marketPriority: ['ML'],
    profile: {
      goalEnvironment: 'low',
      homeAdvantage: 1.10,
      variance: 'low',
      fatigueSensitivity: 1.0,
      marketLiquidity: 'low'
    },
    marketSuitability: { AH: false, OU: false, ML: true },
    apiFootballId: 848,
    status: 'DISABLED',
    cohort: 'LIGUE2',
    minimumHistoricalMatches: 10,
    priority: 3,
    competition_type: 'league',
    tier: 3,
    liquidity_score: 30,
    market_coverage_score: 40,
    validation_priority: 'C',
    is_active_now: false,
    expected_fixture_frequency: 'low',
    market_liquidity_score: 30
  },

  // --- SPRINT 10 ADDITIONS: EUROPE QUALIFICATION & TOURNEYS ---
  {
    id: 'uefa_champions_league_qual',
    name: 'UEFA Champions League Qualification',
    country: 'Europe',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: { goalEnvironment: 'medium', homeAdvantage: 1.08, variance: 'high', fatigueSensitivity: 1.2, marketLiquidity: 'high' },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 9991, // Virtual id to distinguish from main tournament if needed
    status: 'ACTIVE',
    cohort: 'EUROPA',
    priority: 1,
    competition_type: 'cup',
    validation_priority: 'A',
    is_active_now: true,
    expected_fixture_frequency: 'high',
    market_liquidity_score: 95
  },
  {
    id: 'uefa_europa_league_qual',
    name: 'UEFA Europa League Qualification',
    country: 'Europe',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: { goalEnvironment: 'medium', homeAdvantage: 1.08, variance: 'medium-high', fatigueSensitivity: 1.1, marketLiquidity: 'high' },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 9992,
    status: 'ACTIVE',
    cohort: 'EUROPA',
    priority: 1,
    competition_type: 'cup',
    validation_priority: 'A',
    is_active_now: true,
    expected_fixture_frequency: 'high',
    market_liquidity_score: 90
  },
  {
    id: 'uefa_conference_league_qual',
    name: 'UEFA Conference League Qualification',
    country: 'Europe',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: { goalEnvironment: 'medium', homeAdvantage: 1.08, variance: 'medium', fatigueSensitivity: 1.0, marketLiquidity: 'medium' },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 9993,
    status: 'ACTIVE',
    cohort: 'EUROPA',
    priority: 1,
    competition_type: 'cup',
    validation_priority: 'A',
    is_active_now: true,
    expected_fixture_frequency: 'high',
    market_liquidity_score: 80
  },

  // --- SPRINT 10 ADDITIONS: ACTIVE DOMESTIC EUROPE ---
  {
    id: 'nor_eliteserien',
    name: 'Norway Eliteserien',
    country: 'Norway',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: { goalEnvironment: 'high', homeAdvantage: 1.15, variance: 'medium', fatigueSensitivity: 1.0, marketLiquidity: 'medium' },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 103,
    status: 'ACTIVE',
    cohort: 'OTHER',
    priority: 2,
    competition_type: 'league',
    validation_priority: 'A',
    is_active_now: true,
    expected_fixture_frequency: 'medium',
    market_liquidity_score: 75
  },
  {
    id: 'swe_allsvenskan',
    name: 'Sweden Allsvenskan',
    country: 'Sweden',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: { goalEnvironment: 'medium-high', homeAdvantage: 1.12, variance: 'medium', fatigueSensitivity: 1.0, marketLiquidity: 'medium' },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 113,
    status: 'ACTIVE',
    cohort: 'OTHER',
    priority: 2,
    competition_type: 'league',
    validation_priority: 'A',
    is_active_now: true,
    expected_fixture_frequency: 'medium',
    market_liquidity_score: 75
  },
  {
    id: 'dnk_superliga',
    name: 'Denmark Superliga',
    country: 'Denmark',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: { goalEnvironment: 'medium', homeAdvantage: 1.12, variance: 'medium', fatigueSensitivity: 1.0, marketLiquidity: 'medium' },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 119,
    status: 'ACTIVE',
    cohort: 'OTHER',
    priority: 2,
    competition_type: 'league',
    validation_priority: 'A',
    is_active_now: true,
    expected_fixture_frequency: 'medium',
    market_liquidity_score: 80
  },
  {
    id: 'fin_veikkausliiga',
    name: 'Finland Veikkausliiga',
    country: 'Finland',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: { goalEnvironment: 'medium-low', homeAdvantage: 1.10, variance: 'medium', fatigueSensitivity: 1.0, marketLiquidity: 'low' },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 244,
    status: 'ACTIVE',
    cohort: 'OTHER',
    priority: 2,
    competition_type: 'league',
    validation_priority: 'A',
    is_active_now: true,
    expected_fixture_frequency: 'medium',
    market_liquidity_score: 70
  },
  {
    id: 'isl_besta_deild',
    name: 'Iceland Besta deild',
    country: 'Iceland',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: { goalEnvironment: 'high', homeAdvantage: 1.15, variance: 'high', fatigueSensitivity: 1.1, marketLiquidity: 'low' },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 365,
    status: 'ACTIVE',
    cohort: 'OTHER',
    priority: 2,
    competition_type: 'league',
    validation_priority: 'A',
    is_active_now: true,
    expected_fixture_frequency: 'medium',
    market_liquidity_score: 70
  },
  {
    id: 'irl_premier_div',
    name: 'Ireland Premier Division',
    country: 'Ireland',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: { goalEnvironment: 'medium-low', homeAdvantage: 1.10, variance: 'low', fatigueSensitivity: 1.0, marketLiquidity: 'low' },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 357,
    status: 'ACTIVE',
    cohort: 'OTHER',
    priority: 2,
    competition_type: 'league',
    validation_priority: 'A',
    is_active_now: true,
    expected_fixture_frequency: 'medium',
    market_liquidity_score: 70
  },

  // --- SPRINT 10 ADDITIONS: LATIN AMERICA ---
  {
    id: 'bra_serie_a',
    name: 'Brazil Serie A',
    country: 'Brazil',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: { goalEnvironment: 'medium-low', homeAdvantage: 1.18, variance: 'medium-high', fatigueSensitivity: 1.1, marketLiquidity: 'medium' },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 71,
    status: 'ACTIVE',
    cohort: 'OTHER',
    priority: 2,
    competition_type: 'league',
    validation_priority: 'A',
    is_active_now: true,
    expected_fixture_frequency: 'high',
    market_liquidity_score: 85
  },
  {
    id: 'arg_primera_div',
    name: 'Argentina Primera Division',
    country: 'Argentina',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: { goalEnvironment: 'low', homeAdvantage: 1.15, variance: 'medium', fatigueSensitivity: 1.0, marketLiquidity: 'medium' },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 73,
    status: 'ACTIVE',
    cohort: 'OTHER',
    priority: 2,
    competition_type: 'league',
    validation_priority: 'A',
    is_active_now: true,
    expected_fixture_frequency: 'high',
    market_liquidity_score: 80
  },
  {
    id: 'chl_primera_div',
    name: 'Chile Primera Division',
    country: 'Chile',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: { goalEnvironment: 'medium', homeAdvantage: 1.10, variance: 'medium-high', fatigueSensitivity: 1.0, marketLiquidity: 'low' },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 265,
    status: 'ACTIVE',
    cohort: 'OTHER',
    priority: 2,
    competition_type: 'league',
    validation_priority: 'A',
    is_active_now: true,
    expected_fixture_frequency: 'medium',
    market_liquidity_score: 75
  },
  {
    id: 'col_primera_a',
    name: 'Colombia Primera A',
    country: 'Colombia',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: { goalEnvironment: 'medium-low', homeAdvantage: 1.15, variance: 'medium', fatigueSensitivity: 1.0, marketLiquidity: 'low' },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 239,
    status: 'ACTIVE',
    cohort: 'OTHER',
    priority: 2,
    competition_type: 'league',
    validation_priority: 'A',
    is_active_now: true,
    expected_fixture_frequency: 'medium',
    market_liquidity_score: 75
  },
  {
    id: 'ecu_liga_pro',
    name: 'Ecuador Liga Pro',
    country: 'Ecuador',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: { goalEnvironment: 'medium', homeAdvantage: 1.15, variance: 'medium-high', fatigueSensitivity: 1.0, marketLiquidity: 'low' },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 242,
    status: 'ACTIVE',
    cohort: 'OTHER',
    priority: 2,
    competition_type: 'league',
    validation_priority: 'A',
    is_active_now: true,
    expected_fixture_frequency: 'medium',
    market_liquidity_score: 70
  },
  {
    id: 'ury_primera_div',
    name: 'Uruguay Primera Division',
    country: 'Uruguay',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: { goalEnvironment: 'medium-low', homeAdvantage: 1.12, variance: 'medium', fatigueSensitivity: 1.0, marketLiquidity: 'low' },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 270,
    status: 'ACTIVE',
    cohort: 'OTHER',
    priority: 2,
    competition_type: 'league',
    validation_priority: 'A',
    is_active_now: true,
    expected_fixture_frequency: 'medium',
    market_liquidity_score: 70
  },
  {
    id: 'pry_primera_div',
    name: 'Paraguay Primera Division',
    country: 'Paraguay',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: { goalEnvironment: 'medium', homeAdvantage: 1.12, variance: 'medium', fatigueSensitivity: 1.0, marketLiquidity: 'low' },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 252,
    status: 'ACTIVE',
    cohort: 'OTHER',
    priority: 2,
    competition_type: 'league',
    validation_priority: 'A',
    is_active_now: true,
    expected_fixture_frequency: 'medium',
    market_liquidity_score: 70
  },
  {
    id: 'per_liga_1',
    name: 'Peru Liga 1',
    country: 'Peru',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: { goalEnvironment: 'medium-high', homeAdvantage: 1.15, variance: 'high', fatigueSensitivity: 1.0, marketLiquidity: 'low' },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 281,
    status: 'ACTIVE',
    cohort: 'OTHER',
    priority: 2,
    competition_type: 'league',
    validation_priority: 'A',
    is_active_now: true,
    expected_fixture_frequency: 'medium',
    market_liquidity_score: 70
  },

  // --- SPRINT 10 ADDITIONS: ASIA ---
  {
    id: 'jpn_j1_league',
    name: 'Japan J1 League',
    country: 'Japan',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: { goalEnvironment: 'medium', homeAdvantage: 1.08, variance: 'medium', fatigueSensitivity: 1.0, marketLiquidity: 'medium' },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 98,
    status: 'ACTIVE',
    cohort: 'OTHER',
    priority: 2,
    competition_type: 'league',
    validation_priority: 'A',
    is_active_now: true,
    expected_fixture_frequency: 'medium',
    market_liquidity_score: 80
  },
  {
    id: 'kor_k_league',
    name: 'K League',
    country: 'South Korea',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: { goalEnvironment: 'medium-low', homeAdvantage: 1.08, variance: 'medium', fatigueSensitivity: 1.0, marketLiquidity: 'medium' },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 292,
    status: 'ACTIVE',
    cohort: 'OTHER',
    priority: 2,
    competition_type: 'league',
    validation_priority: 'A',
    is_active_now: true,
    expected_fixture_frequency: 'medium',
    market_liquidity_score: 75
  },
  {
    id: 'chn_super_league',
    name: 'China Super League',
    country: 'China',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: { goalEnvironment: 'medium', homeAdvantage: 1.10, variance: 'high', fatigueSensitivity: 1.1, marketLiquidity: 'low' },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 251,
    status: 'ACTIVE',
    cohort: 'OTHER',
    priority: 2,
    competition_type: 'league',
    validation_priority: 'A',
    is_active_now: true,
    expected_fixture_frequency: 'medium',
    market_liquidity_score: 70
  },
  {
    id: 'sau_pro_league',
    name: 'Saudi Pro League',
    country: 'Saudi Arabia',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: { goalEnvironment: 'high', homeAdvantage: 1.10, variance: 'medium-high', fatigueSensitivity: 1.0, marketLiquidity: 'medium' },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 307,
    status: 'ACTIVE',
    cohort: 'OTHER',
    priority: 2,
    competition_type: 'league',
    validation_priority: 'A',
    is_active_now: true,
    expected_fixture_frequency: 'medium',
    market_liquidity_score: 75
  },
  {
    id: 'uae_pro_league',
    name: 'UAE Pro League',
    country: 'UAE',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: { goalEnvironment: 'medium-high', homeAdvantage: 1.10, variance: 'high', fatigueSensitivity: 1.0, marketLiquidity: 'low' },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 301,
    status: 'ACTIVE',
    cohort: 'OTHER',
    priority: 2,
    competition_type: 'league',
    validation_priority: 'A',
    is_active_now: true,
    expected_fixture_frequency: 'medium',
    market_liquidity_score: 70
  },
  {
    id: 'qat_stars_league',
    name: 'Qatar Stars League',
    country: 'Qatar',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: { goalEnvironment: 'high', homeAdvantage: 1.10, variance: 'high', fatigueSensitivity: 1.0, marketLiquidity: 'low' },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 305,
    status: 'ACTIVE',
    cohort: 'OTHER',
    priority: 2,
    competition_type: 'league',
    validation_priority: 'A',
    is_active_now: true,
    expected_fixture_frequency: 'medium',
    market_liquidity_score: 70
  },
  {
    id: 'tha_league_1',
    name: 'Thailand League',
    country: 'Thailand',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: { goalEnvironment: 'medium-high', homeAdvantage: 1.12, variance: 'medium', fatigueSensitivity: 1.0, marketLiquidity: 'low' },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 296,
    status: 'ACTIVE',
    cohort: 'OTHER',
    priority: 2,
    competition_type: 'league',
    validation_priority: 'A',
    is_active_now: true,
    expected_fixture_frequency: 'medium',
    market_liquidity_score: 70
  },
  {
    id: 'idn_liga_1',
    name: 'Indonesia Liga 1',
    country: 'Indonesia',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: { goalEnvironment: 'medium', homeAdvantage: 1.15, variance: 'high', fatigueSensitivity: 1.0, marketLiquidity: 'low' },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 310,
    status: 'ACTIVE',
    cohort: 'OTHER',
    priority: 2,
    competition_type: 'league',
    validation_priority: 'A',
    is_active_now: true,
    expected_fixture_frequency: 'medium',
    market_liquidity_score: 70
  },

  // --- SPRINT 10 ADDITIONS: USA ---
  {
    id: 'usa_mls',
    name: 'MLS',
    country: 'USA',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: { goalEnvironment: 'high', homeAdvantage: 1.15, variance: 'high', fatigueSensitivity: 1.2, marketLiquidity: 'medium' },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 253,
    status: 'ACTIVE',
    cohort: 'OTHER',
    priority: 2,
    competition_type: 'league',
    validation_priority: 'A',
    is_active_now: true,
    expected_fixture_frequency: 'medium',
    market_liquidity_score: 80
  },

  // --- CANONICAL COMPETITIONS ADDITIONS (EPIC 42.0) ---
  {
    id: 'eng_championship',
    name: 'Championship',
    country: 'England',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: { goalEnvironment: 'medium', homeAdvantage: 1.10, variance: 'medium-high', fatigueSensitivity: 1.1, marketLiquidity: 'high' },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 40,
    footballDataId: 2016,
    status: 'ACTIVE',
    cohort: 'OTHER',
    priority: 2,
    competition_type: 'league',
    validation_priority: 'A',
    is_active_now: true,
    expected_fixture_frequency: 'high',
    market_liquidity_score: 85
  },
  {
    id: 'eng_league_one',
    name: 'League One',
    country: 'England',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: { goalEnvironment: 'medium-high', homeAdvantage: 1.10, variance: 'medium', fatigueSensitivity: 1.0, marketLiquidity: 'medium' },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 41,
    status: 'ACTIVE',
    cohort: 'OTHER',
    priority: 3,
    competition_type: 'league',
    validation_priority: 'B',
    is_active_now: true,
    expected_fixture_frequency: 'high',
    market_liquidity_score: 70
  },
  {
    id: 'eng_league_two',
    name: 'League Two',
    country: 'England',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: { goalEnvironment: 'medium', homeAdvantage: 1.10, variance: 'medium-high', fatigueSensitivity: 1.0, marketLiquidity: 'medium' },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 42,
    status: 'ACTIVE',
    cohort: 'OTHER',
    priority: 3,
    competition_type: 'league',
    validation_priority: 'B',
    is_active_now: true,
    expected_fixture_frequency: 'high',
    market_liquidity_score: 65
  },
  {
    id: 'por_primeira_liga',
    name: 'Primeira Liga',
    country: 'Portugal',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: { goalEnvironment: 'medium', homeAdvantage: 1.14, variance: 'medium', fatigueSensitivity: 1.0, marketLiquidity: 'high' },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 128,
    footballDataId: 2017,
    status: 'ACTIVE',
    cohort: 'OTHER',
    priority: 2,
    competition_type: 'league',
    validation_priority: 'A',
    is_active_now: true,
    expected_fixture_frequency: 'high',
    market_liquidity_score: 85
  },
  {
    id: 'esp_segunda_division',
    name: 'Segunda División',
    country: 'Spain',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: { goalEnvironment: 'low', homeAdvantage: 1.12, variance: 'low', fatigueSensitivity: 1.0, marketLiquidity: 'medium' },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 141,
    status: 'ACTIVE',
    cohort: 'OTHER',
    priority: 2,
    competition_type: 'league',
    validation_priority: 'A',
    is_active_now: true,
    expected_fixture_frequency: 'high',
    market_liquidity_score: 75
  },
  {
    id: 'ned_eredivisie',
    name: 'Eredivisie',
    country: 'Netherlands',
    type: 'club',
    enabled: true,
    marketPriority: ['AH', 'OU', 'ML'],
    profile: { goalEnvironment: 'high', homeAdvantage: 1.12, variance: 'medium-high', fatigueSensitivity: 1.0, marketLiquidity: 'high' },
    marketSuitability: { AH: true, OU: true, ML: true },
    apiFootballId: 254,
    footballDataId: 2003,
    status: 'ACTIVE',
    cohort: 'OTHER',
    priority: 2,
    competition_type: 'league',
    validation_priority: 'A',
    is_active_now: true,
    expected_fixture_frequency: 'high',
    market_liquidity_score: 85
  }
];

export function getLeagueConfig(apiFootballId: number | string): LeagueConfig | null {
  const lookupStr = String(apiFootballId).toLowerCase();
  return LEAGUE_REGISTRY.find(l => 
    String(l.apiFootballId) === lookupStr || 
    l.id.toLowerCase() === lookupStr || 
    l.name.toLowerCase() === lookupStr
  ) ?? null;
}

export function getLeagueConfigById(id: string): LeagueConfig | null {
  return LEAGUE_REGISTRY.find(l => l.id === id) ?? null;
}
