/**
 * Module 7: Decision Governance Engine — Types
 * Defines the immutable Event Sourcing ledger schemas and CQRS boundaries.
 */

// ─── 1. Core Event Envelope (Institutional Invariant) ──────────────────────────

export type EventType = 
  | 'PredictionCreated' 
  | 'GovernanceReviewed'
  | 'HumanOverrideRequested'
  | 'HumanOverrideApproved'
  | 'HumanOverrideRejected'
  | 'DecisionApproved'
  | 'DecisionRejected'
  | 'ExecutionSkipped'
  | 'SettlementRecorded';

export interface BaseEventEnvelope<T = any> {
  event_id: string; // ULID
  event_type: EventType;
  
  aggregate_id: string; // UUID (Decision / Prediction ID)
  correlation_id: string; // Root trace ID (e.g. Match ID)
  causation_id: string; // Event ID that triggered this one
  
  version: number; // For Optimistic Concurrency
  schema_version: string; // e.g. "v1.0" for backward compatibility parsing
  
  actor: string; // "system", "user-id", "governance-engine"
  event_time: string; // When the domain event actually occurred
  processed_at: string; // When the event was physically appended to the ledger
  
  payload: T;
}

// ─── 2. Commands & Idempotency ──────────────────────────────────────────────────

export interface BaseCommand<T = any> {
  command_id: string;
  idempotency_key: string;
  correlation_id: string;
  actor: string;
  payload: T;
}

// ─── 3. Governance Rule & Plugin Contracts ──────────────────────────────────────

export type RuleStatus = 'PASS' | 'VETO' | 'SCORE' | 'INFO';

/** Every Rule explicitly defines its provenance for auditability */
export interface RuleProvenance {
  rule_id: string;
  rule_version: string;
  configuration_version: string;
  override_policy_version?: string; // If this result came from a human override
  execution_time_ms: number;
}

export type GovernanceDecisionCode = 
  | 'GV001_HEALTH_BELOW_THRESHOLD'
  | 'GV002_RELIABILITY_TOO_LOW'
  | 'GV003_EVIDENCE_INSUFFICIENT'
  | 'GV004_MANUAL_OVERRIDE'
  | 'GV005_MARKET_SUSPENDED'
  | 'GV200_APPROVED'
  | 'GV201_SCORE_ADJUSTMENT';

export interface RuleResult {
  status: RuleStatus;
  code: GovernanceDecisionCode;
  scoreAdjustment?: number; // E.g., -15 or +10
  reason: string;
  provenance: RuleProvenance;
}

export type GovernanceVerdict = 'EXECUTE' | 'REJECT' | 'HOLD' | 'PAPER_ONLY';

/**
 * Interface that all Governance Engines (RuleBased, Bayesian, LLM) must implement.
 */
export interface GovernanceEnginePlugin {
  evaluate(
    prediction: Readonly<any>, // Immutable Prediction (M2)
    health: Readonly<any>,     // Immutable Health (M3)
    evidence: Readonly<any>,   // Immutable Evidence (M5)
    configVersion: string
  ): {
    verdict: GovernanceVerdict;
    decisionConfidence: number; // Distinct from Prediction Confidence!
    ruleResults: RuleResult[];
    explanation: string;
  };
}

// ─── 4. Override Authorization Contracts ───────────────────────────────────────

export type OverrideRole = 'MAKER' | 'REVIEWER' | 'APPROVER' | 'EXECUTOR';

export interface OverridePermission {
  userId: string;
  roles: OverrideRole[];
}

// ─── 5. Aggregates & Projections ────────────────────────────────────────────────

/** 
 * DecisionReadModel (CQRS Read-Side Projection)
 * Synchronously built from the Event Store to populate Dashboards without replaying.
 */
export interface DecisionReadModel {
  decision_id: string; // The active decision
  parent_decision_id?: string; // If this is an override, link to the parent
  override_chain_depth: number; // 0 for system, 1 for first override, 2 for nested...
  
  correlation_id: string;
  current_state: 'PENDING' | 'ASSIGNED' | 'UNDER_REVIEW' | 'APPROVED' | 'REJECTED' | 'OVERRIDE_PENDING';
  
  // Assignment Ownership
  assigned_to?: string;
  assigned_at?: string;
  assignment_reason?: string;
  
  prediction_probability: number;
  decision_confidence: number; // Generated by Governance, NOT Model
  
  final_verdict?: GovernanceVerdict;
  
  created_at: string;
  last_updated_at: string;
  last_event_version: number;
  projection_hash?: string; // Checksum to detect nondeterminism during replay
}
