import { supabase } from '../supabase.server';

interface DailyMetrics {
  signalsAnalyzed: number;
  betsTaken: number;
  skips: number;
  roiUnits: number;
  avgClv: number;
  sampleSize: number;
  forensicScore: number;
}

export async function generateDailyReport(targetDate?: string): Promise<any> {
  const dateStr = targetDate || new Date().toISOString().split('T')[0];
  console.log(`📊 [Forensic Engine] Generating report for date: ${dateStr}`);

  // 1. Fetch prediction ledger entries for the date
  const { data: ledgerEntries, error: ledgerErr } = await supabase
    .from('prediction_ledger')
    .select('id, market, selection, result_status, roi, published_at');

  if (ledgerErr) {
    throw new Error(`Failed to query prediction_ledger: ${ledgerErr.message}`);
  }

  // Filter for items published on targetDate
  const dailyLedger = (ledgerEntries || []).filter(item => {
    return new Date(item.published_at).toISOString().split('T')[0] === dateStr;
  });

  const ledgerIds = dailyLedger.map(item => item.id);

  // 2. Fetch decisions corresponding to the ledger entries
  let decisions: any[] = [];
  if (ledgerIds.length > 0) {
    const { data: decData } = await supabase
      .from('prediction_decisions')
      .select('*')
      .in('prediction_ledger_id', ledgerIds);
    decisions = decData || [];
  }

  // 3. Fetch paper trades matching the decisions
  let paperTrades: any[] = [];
  if (ledgerIds.length > 0) {
    const { data: ptData } = await supabase
      .from('paper_trades')
      .select('*')
      .in('prediction_ledger_id', ledgerIds);
    paperTrades = ptData || [];
  }

  // 4. Calculate metrics
  const signalsAnalyzed = dailyLedger.length;
  const betsTaken = decisions.filter(d => d.decision === 'BET').length;
  const skips = decisions.filter(d => d.decision === 'SKIP').length;
  
  // Calculate ROI & CLV from paper trades settled today or matching these signals
  const settledTrades = paperTrades.filter(pt => pt.status !== 'PENDING');
  const roiUnits = settledTrades.reduce((sum, pt) => sum + (pt.pnl_units || 0), 0);
  
  const clvTrades = settledTrades.filter(pt => pt.clv_percentage !== null);
  const avgClv = clvTrades.length > 0
    ? clvTrades.reduce((sum, pt) => sum + Number(pt.clv_percentage), 0) / clvTrades.length
    : 0.0;
  
  const sampleSize = settledTrades.length;

  // Forensic Score (0-100 index based on calibration and efficiency)
  const baseScore = 75;
  const clvModifier = avgClv * 2.5;
  const pnlModifier = roiUnits * 3.0;
  const forensicScore = Math.max(0, Math.min(100, Math.round(baseScore + clvModifier + pnlModifier)));

  // 5. Content Safety Filter
  const sanitizeText = (text: string): string => {
    return text
      .replace(/guaranteed win|sure win|100% win|can't lose/gi, 'model detected high-probability value edge')
      .replace(/guarantee profit|guaranteed returns|make money|guaranteed yield/gi, 'historical sample tracked performance')
      .replace(/you should bet|place bet on|recommend betting|sure bets|best picks/gi, 'model flagged quantitative inefficiency');
  };

  // 6. Draft Content Generation
  const betRatioText = signalsAnalyzed > 0 ? ((betsTaken / signalsAnalyzed) * 100).toFixed(1) : '0.0';

  const twitterDraft = sanitizeText(
    `📊 [HandicapLab Model Forensics Audit: ${dateStr}]\n\n` +
    `• Signals Evaluated: ${signalsAnalyzed}\n` +
    `• Actionable Executions (BET): ${betsTaken} (${betRatioText}% filter pass-rate)\n` +
    `• Skipping Decisions: ${skips}\n` +
    `• Unit PnL (Settled Today): ${roiUnits >= 0 ? '+' : ''}${roiUnits.toFixed(2)}u\n` +
    `• Average CLV edge: ${avgClv >= 0 ? '+' : ''}${avgClv.toFixed(2)}%\n\n` +
    `Forensic calibration index registers at ${forensicScore}/100. Tracked performance only. Simulation results, not betting advice. 🛡️`
  );

  const redditDraft = sanitizeText(
    `### HandicapLab Quantitative Intelligence & Forensic Audit Report — ${dateStr}\n\n` +
    `Here is the automated daily forensic audit of ensembled model predictions generated by our pre-match pipeline.\n\n` +
    `#### Key Distribution Metrics:\n` +
    `- **Total Predictions Logs**: ${signalsAnalyzed}\n` +
    `- **Engine Execution Rate (BET)**: ${betsTaken} picks (${betRatioText}% of total)\n` +
    `- **Engine Avoidance Rate (SKIP)**: ${skips} skips\n` +
    `- **Verifiable Yield (Settled Sample)**: ${roiUnits >= 0 ? '+' : ''}${roiUnits.toFixed(2)} units (Sample size: ${sampleSize})\n` +
    `- **Model CLV efficiency**: ${avgClv >= 0 ? '+' : ''}${avgClv.toFixed(2)}% average edge\n` +
    `- **Calibration Forensic Score**: **${forensicScore}/100**\n\n` +
    `#### Quantitative Summary:\n` +
    `The model detected inefficiencies across the analyzed markets. We maintain a strict rule engine where paper trades are populated only if model confidence and expected values exceed configured limits. These metrics represent historical sample tracked performance in simulation.`
  );

  const telegramDraft = sanitizeText(
    `🎯 *HandicapLab Model Analytics Daily Forensics (${dateStr})*\n\n` +
    `• *Signals Evaluated*: ${signalsAnalyzed}\n` +
    `• *BET Decisions*: ${betsTaken} (${betRatioText}%)\n` +
    `• *SKIP Decisions*: ${skips}\n` +
    `• *Today PnL*: ${roiUnits >= 0 ? '+' : ''}${roiUnits.toFixed(2)}u\n` +
    `• *Avg CLV*: ${avgClv >= 0 ? '+' : ''}${avgClv.toFixed(2)}%\n` +
    `• *Calibration Score*: *${forensicScore}/100*\n\n` +
    `_This represents historical sample tracked performance. All signals are locked and verified post-match. Model simulation results, not financial advice._`
  );

  const generatedContent = {
    twitter: twitterDraft,
    reddit: redditDraft,
    telegram: telegramDraft
  };

  // 7. Save report to database as DRAFT
  const { data: newReport, error: saveErr } = await supabase
    .from('forensic_reports')
    .insert({
      report_type: 'daily',
      date: dateStr,
      signals_analyzed: signalsAnalyzed,
      bets_taken: betsTaken,
      skips: skips,
      roi_units: roiUnits,
      avg_clv: avgClv,
      sample_size: sampleSize,
      forensic_score: forensicScore,
      generated_content: generatedContent,
      status: 'DRAFT'
    })
    .select('*')
    .maybeSingle();

  if (saveErr) {
    console.error('Failed to save forensic report draft:', saveErr);
    throw new Error(`Failed to save report: ${saveErr.message}`);
  }

  return {
    success: true,
    report: newReport
  };
}
