CREATE TABLE IF NOT EXISTS calibration_registry (
    id SERIAL PRIMARY KEY,
    method VARCHAR(100) NOT NULL,
    dataset VARCHAR(255) NOT NULL,
    protocol VARCHAR(255) NOT NULL,
    ece DOUBLE PRECISION NOT NULL,
    brier DOUBLE PRECISION NOT NULL,
    log_loss DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    approved_at TIMESTAMP WITH TIME ZONE,
    champion BOOLEAN DEFAULT FALSE
);
